Revert "Attempt to fix issue (references: https://stackoverflow.com/a/71153484/13115170 and https://github.com/open-mmlab/mmdetection/issues/5724#issuecomment-1016415834): "AttributeError: module 'browserist' has no attribute '__version__'""
This reverts commit e146a696238e94f8af7dd87bd58f7c1a75fccf6f.