Attempt to fix issue by separating download helper methods to its own entity: "ImportError: cannot import name 'BrowserDriver' from partially initialized module 'browserist.model.browser.base.driver' (most likely due to a circular import) (/Users/jakobbagterp/Code/browserist/src/browserist/model/browser/base/driver.py)"