Attempt to fix issue "ImportError: cannot import name 'default_file_name' from partially initialized module 'browserist.helper.screenshot' (most likely due to a circular import)"