Revert "Attempted fix of MyPy issue: "src\browserist\factory\internet_explorer.py:9: error: Unused "type: ignore" comment  [unused-ignore]""
This reverts commit 4bdc1673ecac2ca44d3cbddd90f369479b26a282.