Refactor and move retry helper methods into separate iteration helper to fix issue: "ImportError: cannot import name 'BrowserDriver' from partially initialized module 'browserist.model.browser.base.driver' (most likely due to a circular import) (/Users/jakobbagterp/Documents/Kodeprojekter/browserist/src/browserist/model/browser/base/driver.py)"